### ISSUE TITLE
Set up nginx

### ISSUE THREAD

**Issue by matthew-white** [nafundi/super-adventure#10]
We need something like this as a more permanent solution for CORS.

**Comment by ggalmazor** [comment]
CORS consists mainly on doing the following things:
- The browser sets an **Origin** header in each request identifying the domain name from which the request is originated
- The server sets an **Access-Control-Allow-Origin** header (among others) in each response indicating which domain names are allowed to interact with the server.

I understand that Axios or event the Fetch API can add the **Origin** header with each request and Jubilant should add CORS headers on each response.

Jubilant should also respond to pre-flight OPTION request that the browser often makes before the real request to be sure beforehand that the request can be made.

Jubilant should use CORS header to indicate which origins, methods and headers are allowed, as well as which headers should be exposed to the browser.

More info about CORS:
- https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
- https://www.securityninja.io/understanding-cross-origin-resource-sharing-cors/

**Comment by matthew-white** [comment]
I haven't used nginx before, but my understanding from @clint-tseng was that we could use nginx to set up a server that hosts both Jubilant and Super Adventure on the same domain. That way requests from Super Adventure to Jubilant wouldn't be cross-origin, saving us the pre-flight request and maybe aiding in debugging. @clint-tseng, would you add anything else about our plans for nginx? @ggalmazor, what do you think of that plan?

**Comment by matthew-white** [comment]
Note to self: if we set up nginx, we would then have to change the Axios base URL set in `main.js`.

**Comment by ggalmazor** [comment]
Looks good!

**Comment by clint-tseng** [comment]
I would only perhaps add that we should set the dev server up with basic SSL termination with a self-signed cert so we're as close to production as possible (eg verifying cookie settings, etc).

**Comment by matthew-white** [comment]
We're going to use a modified version of the nginx configuration from `effective-spork`, focusing on the mod proxy and foregoing SSL for now.
