### ISSUE TITLE
Messaging for when fetching data takes a while

### ISSUE THREAD

**Issue by matthew-white** [nafundi/super-adventure#12]
Right now Super Adventure doesn't indicate to the end user that it is in the process of fetching data (for example, the list of forms or submissions). How about we add messaging for when that fetching takes a while?

**Comment by ggalmazor** [comment]
I could unify the way we give this kind of information to the user, to always solve the same things with the same tools. For example:
- Informative messages could go on a toast that disappears automatically after 5 seconds
- Error messages could go on a permanent toast and require user interaction to hide them
- Async tasks that take some time could trigger a spinner to start spinning on a toolbar with a tooltip that explains what's going on.

This UI components could be transversal to the application and could be triggered through explicit collaboration (through services that are injected into Vue components) or implicitly through events.

The goal would be to always use the same UI artifacts for each kind of posible message for the user. The same reasoning could be followed for confirmation dialogs and modal dialogs...

**Comment by matthew-white** [comment]
#20 added a loading message, so I'm going to close this issue, though I'm sure we'll continue to tweak the UX around loading and errors.
