### ISSUE TITLE
Suggestion: Use standard HTML5 APIs

### ISSUE THREAD

**Issue by ggalmazor** [nafundi/super-adventure#13]
For example, [Fetch API](https://developer.mozilla.org/es/docs/Web/API/Fetch_API) is broadly supported since last year: http://caniuse.com/#feat=fetch
(this would replace Axios)

**Comment by matthew-white** [comment]
I think we're trying to maintain some IE support, but I also see that a polyfill is available for IE 10+. Is that what would you recommend?

**Comment by ggalmazor** [comment]
No, nothing to do with IE. it’s about using the native JavaScript HTML5 standard APIs. Before the Fetch API existed you had to use some library (historically jQuery) to make Ajax calls to a server. 

In our case you’re using Axios, buy now that’s not necessary because there is already a modern API in the language to do that.

**Comment by matthew-white** [comment]
Just discussed with @ggalmazor, and because we're still trying to support IE, `fetch()` isn't available without a polyfill, so we're going to continue with Axios until we drop IE support. @ggalmazor notes that it should be relatively easy to switch out Axios for `fetch()` when that time comes.
