### ISSUE TITLE
Add file-level copyright notices and license information

### ISSUE THREAD

**Issue by matthew-white** [nafundi/super-adventure#16]
We'll continue doing this once we decide on the app's name.

**Comment by matthew-white** [comment]
It's felt a little odd to have some files in Super Adventure with file-level copyright/license information and some without, so I’ve been continuing to add that information to new files. (It's also been nice to get into the habit.) I figure it shouldn’t be too hard to swap out “Super Adventure” for the new name once we decide on that... @lognaturel, does it sound like that strategy could work?

**Comment by lognaturel** [comment]
Works for me!

**Comment by matthew-white** [comment]
Sounds good! I'll go ahead and close this issue then.
