### ISSUE TITLE
Update dashboard

### ISSUE THREAD

**Issue by matthew-white** [nafundi/super-adventure#8]
What should go in the dashboard?

**Comment by lognaturel** [comment]
This is going to be where mental models and usage comes in. Do people think about all of the data coming into their server as related? Is each form entirely separate in their minds? How often does it make sense for several forms to be grouped? @yanokwa

**Comment by matthew-white** [comment]
Maybe it only makes sense to add a dashboard once we have campaigns? I think that campaigns will be a natural grouping unit for forms, but without them, a single server's forms might not all be related. Maybe before we implement campaigns, the landing page can just be the forms list?

**Comment by lognaturel** [comment]
That is all sounding good to me.

**Comment by matthew-white** [comment]
Sounds good! I'll close the issue for now, but we can revisit once we get to campaigns.
